### ISSUE TITLE
auto import not working

### ISSUE THREAD

**Issue by Kiansa** [gaetansenn/vue3-carousel-nuxt#7]
I get this error when I use this module .
```
500
Cannot destructure property 'dir' of 'config' as it is undefined.

at Navigation (http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/vue3-carousel_dist_carousel.js?v=109989b9:36722:17)
at renderComponentRoot (http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-PHJDBFYG.js?v=109989b9:2334:31)
at ReactiveEffect.componentUpdateFn [as fn] (http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-PHJDBFYG.js?v=109989b9:7417:46)
at ReactiveEffect.run (http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-PHJDBFYG.js?v=109989b9:421:19)
at instance.update (http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-PHJDBFYG.js?v=109989b9:7548:17)
at setupRenderEffect (http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-PHJDBFYG.js?v=109989b9:7558:5)
at mountComponent (http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-PHJDBFYG.js?v=109989b9:7326:7)
at processComponent (http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-PHJDBFYG.js?v=109989b9:7280:9)
at patch (http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-PHJDBFYG.js?v=109989b9:6750:11)
at mountChildren (http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-PHJDBFYG.js?v=109989b9:6998:7)
```
when I explicitly import it like below, it works fine 
`import { Carousel, Slide, Navigation, Pagination } from 'vue3-carousel'`

**Comment by magecommerce** [comment]
yes same issue

**Comment by gaetansenn** [comment]
Hello guys,

Just tested with a new nuxt 3 project installing the module and there is no problem.

Can you share a reproduction link such as this (https://github.com/nuxt/ui/issues/new?assignees=&labels=bug&projects=&template=bug-report.yml) ? 

Thanks

**Comment by Kiansa** [comment]
@gaetansenn @magecommerce  I tried removing the import and confirm that auto import works now. I think this is nuxt issue, I've experienced this with composables not auto importing as well. 
It seems that _nuxt is cached and if you run [nuxi prepare](https://nuxt.com/docs/api/commands/prepare), [nuxi dev](https://nuxt.com/docs/api/commands/dev) or [nuxi build](https://nuxt.com/docs/api/commands/build) it refreshes that directory.

**Comment by TimGuendel** [comment]
Sorry to comment on this closed issue, but I am getting the same issue after updating from Nuxt 3.17.1 to 3.17.5.

` ERROR  Cannot destructure property 'dir' of 'config' as it is undefined.
    at Navigation (node_modules/.pnpm/vue3-carousel@0.3.4_vue@3.5.13_typescript@5.6.3_/node_modules/vue3-carousel/dist/carousel.es.js:697:13)
    at renderComponentRoot (node_modules/.pnpm/@vue+runtime-core@3.5.16/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6512:30)
    at renderComponentSubTree (node_modules/.pnpm/@vue+server-renderer@3.5.16_vue@3.5.16_typescript@5.6.3_/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:672:16)
    at renderComponentVNode (node_modules/.pnpm/@vue+server-renderer@3.5.16_vue@3.5.16_typescript@5.6.3_/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:664:12)
    at renderVNode (node_modules/.pnpm/@vue+server-renderer@3.5.16_vue@3.5.16_typescript@5.6.3_/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:779:14)
    at renderVNodeChildren (node_modules/.pnpm/@vue+server-renderer@3.5.16_vue@3.5.16_typescript@5.6.3_/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:795:5)
    at renderVNode (node_modules/.pnpm/@vue+server-renderer@3.5.16_vue@3.5.16_typescript@5.6.3_/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:767:7)
    at renderVNodeChildren (node_modules/.pnpm/@vue+server-renderer@3.5.16_vue@3.5.16_typescript@5.6.3_/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:795:5)
    at renderElementVNode (node_modules/.pnpm/@vue+server-renderer@3.5.16_vue@3.5.16_typescript@5.6.3_/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:839:9)
    at renderVNode (node_modules/.pnpm/@vue+server-renderer@3.5.16_vue@3.5.16_typescript@5.6.3_/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:777:9)`

Manually importing the carousel did not help - what can I do? 👀

EDIT: Deleting node modules fixed the problem 😶
